version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:3000"
      - "443:3000"
    container_name: gurian-belote-app
    restart: unless-stopped