version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gurian-belote-server
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - server
    container_name: gurian-belote-nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email __SSL_EMAIL__ --agree-tos --no-eff-email -d __DOMAIN_NAME__

volumes:
  certbot-etc:
  certbot-var:
  web-root: