name: Deploy Application to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Clean and copy project files to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf /opt/app/*
          
    - name: Copy project files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/opt/app"
        
    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/app
          sudo docker compose down
          sudo docker system prune -af
          sudo docker compose build --no-cache
          sudo docker compose up -d
          sudo docker system prune -f
